module.exports = {
  name: '债券监管与风险管理',
  prefix: 'antdAdmin',
  ContactsText: 'xxx：xxxxxxxx　|　xxx：xxxxxxxx　|　xxx：xxxxxxxx',
  footerText: '债券监管与风险管理系统 版权所有 © 2017 由 上海证券交易 支持',
  logo: 'https://t.alipayobjects.com/images/T1QUBfXo4fXXXXXXXX.png',
  iconFontUrl: '//at.alicdn.com/t/font_c4y7asse3q1cq5mi.js',
  baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7001'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/user/login',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    dashboard: '/dashboard',
  },
}
